version: "3.8"

services:
  db:
    image: postgres:13
    container_name: restaurant_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  backend:
    env_file:
      - .env
    build:
      context: ./backend
      dockerfile: Containerfile
    container_name: restaurant_backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
      - ./plugins:/plugins
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - LLM_API_KEY=${LLM_API_KEY}
      - OPENAI_API_BASE=${OPENAI_API_BASE}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - LLM_PROVIDER=${LLM_PROVIDER}
      - LLM_MODEL=${LLM_MODEL}

volumes:
  postgres_data:
